Remove inheritance of postgresql::params
Inheritance of postgresql::params by postgresql::repo seemed to cause this error (we are overriding manage_package_repo and version in globals).  Removing inheritance worked with no side effects that we have seen so far.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find scope for postgresql::params at /etc/puppet/environments/myPuppetUpgrade/external/postgresql/manifests/globals.pp:119 on node node.example.com